# Generated by Django 3.2.7 on 2022-03-11 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '2. Games Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(default='4916319787', max_length=30, verbose_name='Phone Number')),
                ('zip_code', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='DE', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Berlin', max_length=180, verbose_name='City')),
                ('region', models.CharField(default='Berlin', max_length=100, verbose_name='Region')),
                ('age', models.CharField(blank=True, max_length=10, null=True, verbose_name='Age')),
                ('skill_level', models.CharField(choices=[('Novice', 'Novice'), ('Advanced Beginner', 'Advanced Beginner'), ('Competent', 'Competent'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], default='Novice', max_length=20, verbose_name='Skill Level')),
                ('game_type', models.CharField(choices=[('Badminton', 'Badminton'), ('Paddle Tennis', 'Paddle Tennis'), ('Squash', 'Sqaush'), ('Table Tennis', 'Table Tennis'), ('Tennis', 'Tennis')], default='Tennis', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='About me')),
                ('is_opponent', models.BooleanField(default=False, verbose_name='Opponent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.gamecategory')),
                ('tennis_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Games',
            },
        ),
    ]
