# Generated by Django 3.2.7 on 2022-04-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_opponent',
            field=models.BooleanField(default=True, verbose_name='Opponent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/imgs/tennis_player_img.png', upload_to='', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='User Rating'),
        ),
    ]
