# Generated by Django 3.2.7 on 2022-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_opponent',
            field=models.BooleanField(default=True, verbose_name='Opponent'),
        ),
    ]
