# Generated by Django 3.1.3 on 2022-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opponent_user',
            field=models.BooleanField(default=False, verbose_name='Opponent'),
        ),
    ]
