# Generated by Django 3.2.7 on 2022-04-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/shrek.png', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
