# Generated by Django 3.2.7 on 2022-04-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220414_0932'),
    ]

    operations = [
    ]
