# Generated by Django 3.2.7 on 2022-04-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220415_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
