# Generated by Django 3.1.3 on 2022-03-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirm_password',
        ),
    ]
