# Generated by Django 3.1.3 on 2022-03-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0003_auto_20220308_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='email',
        ),
    ]
