# Generated by Django 3.1.3 on 2022-03-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0005_auto_20220308_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user_profile',
        ),
    ]
