# Generated by Django 3.1.3 on 2022-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericFileUpload',
        ),
    ]
