# Generated by Django 3.2.7 on 2022-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='User Signed'),
        ),
    ]
