# Generated by Django 3.1.3 on 2022-03-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_auto_20220308_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
