# Generated by Django 3.1.3 on 2022-03-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0007_auto_20220308_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
    ]
